name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Oder den Branch, den du für deine Hauptentwicklung nutzt (z.B. master)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web --release --base-href /heuesenstamm_spielt_flutter/ # Wichtig: Passe <DEIN_REPOSITORY_NAME> an!

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        publish_dir: ./build/web
        force_orphan: true
